"""add id to owl queries

Revision ID: 330e5d362019
Revises: 59268b75a580
Create Date: 2026-05-16 18:58:59.241313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330e5d362019'
down_revision: Union[str, Sequence[str], None] = '59268b75a580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owl_queries', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'owl_queries', ['query'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owl_queries', type_='unique')
    op.drop_column('owl_queries', 'id')
    # ### end Alembic commands ###
