"""change video id to varchar

Revision ID: 3b0d4041155f
Revises: 18a4a067e2a2
Create Date: 2026-05-01 16:36:01.054191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0d4041155f'
down_revision: Union[str, Sequence[str], None] = '18a4a067e2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'id',
               existing_type=sa.String(length=20),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
