"""update pipelines

Revision ID: 51a20156ddbc
Revises: f061948e2f89
Create Date: 2026-05-01 21:35:29.195566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a20156ddbc'
down_revision: Union[str, Sequence[str], None] = 'f061948e2f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('frames_interval', sa.Integer(), nullable=False))
    op.add_column('pipelines', sa.Column('detection_done', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pipelines', sa.Column('transcription_done', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pipelines', sa.Column('description', sa.String(length=1023), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'description')
    op.drop_column('pipelines', 'transcription_done')
    op.drop_column('pipelines', 'detection_done')
    op.drop_column('pipelines', 'frames_interval')
    # ### end Alembic commands ###
