"""add owl table and class mapping

Revision ID: 59268b75a580
Revises: 4762934fca4e
Create Date: 2026-05-16 18:26:19.864985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59268b75a580'
down_revision: Union[str, Sequence[str], None] = '4762934fca4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_classes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('owl_queries',
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['detection_classes.name'], ),
    sa.PrimaryKeyConstraint('query')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owl_queries')
    op.drop_table('detection_classes')
    # ### end Alembic commands ###
