"""add fps to pipline info

Revision ID: 5aa4868d2df5
Revises: 51a20156ddbc
Create Date: 2026-05-02 20:06:08.360698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa4868d2df5'
down_revision: Union[str, Sequence[str], None] = '51a20156ddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('fps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'fps')
    # ### end Alembic commands ###
