"""mv owl_queries to query, rm yolo, add models list

Revision ID: 67044b367181
Revises: 330e5d362019
Create Date: 2026-05-22 20:37:37.390230

"""
from app.database.declarations.detection_models import DetectionModelsEnum
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67044b367181'
down_revision: Union[str, Sequence[str], None] = '330e5d362019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    models = op.create_table('detection_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    data = [
        {"id": DetectionModelsEnum.OWL, "name": "OWL"},
        {"id": DetectionModelsEnum.CLIP, "name": "CLIP"},
    ]
    op.bulk_insert(models, data)

    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_type', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['detection_classes.name'], ),
    sa.ForeignKeyConstraint(['model_type'], ['detection_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.drop_table('yolo_thresholds')
    op.drop_table('owl_queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owl_queries',
    sa.Column('query', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['detection_classes.name'], name=op.f('owl_queries_class_name_fkey')),
    sa.PrimaryKeyConstraint('query', name=op.f('owl_queries_pkey')),
    sa.UniqueConstraint('query', name=op.f('owl_queries_query_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('yolo_thresholds',
    sa.Column('class_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('class_name', name=op.f('yolo_thresholds_pkey'))
    )
    op.drop_table('queries')
    op.drop_table('detection_models')
    # ### end Alembic commands ###
