"""add threshold to queries

Revision ID: 7afa318ef11e
Revises: 67044b367181
Create Date: 2026-05-22 21:25:33.986332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afa318ef11e'
down_revision: Union[str, Sequence[str], None] = '67044b367181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('threshold', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'threshold')
    # ### end Alembic commands ###
