"""add piplines table

Revision ID: f061948e2f89
Revises: 3b0d4041155f
Create Date: 2026-05-01 19:47:14.265455

"""
from app.database.declarations.pipeline import PipelineStatusesEnum, PIPELINE_STATUSES_DESCRIPTION
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f061948e2f89'
down_revision: Union[str, Sequence[str], None] = '3b0d4041155f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pipeline_statuses = op.create_table('pipeline_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    data = []
    for status in PipelineStatusesEnum:
        data.append(
            {
                "id": status.value,
                "name": status.name,
                "description": PIPELINE_STATUSES_DESCRIPTION[status],
            }
        )
    op.bulk_insert(pipeline_statuses, data)
    
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['status'], ['pipeline_statuses.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelines')
    op.drop_table('pipeline_statuses')
    # ### end Alembic commands ###
